# Independent settings for the local costmap
local_costmap:
  # attention, the order and combination method matters
  plugins:
    - name: stvl_rgbd_layer
      type: 'spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer'
    - name: inflation_layer
      type: 'costmap_2d::InflationLayer'
